songAri = []
song_list = [
    "Problem",
    "Bang Bang",
    "Love me Harder",
    "Break Free",
    "One Last Time",
    "No Tears Left to Cry)",
    "Side to Side",
    "Imagine",
    "Santa Tell Me",
    "7 rings",
    "Thank u next",
    "Save your Tears",
    "Motive",
    "pov",
    "God is woman",
    "Into you",
    "Dangerous Woman",
    "break up with your girlfriend, i'm bored",
]