SONGS = [
    {"id":52907687,"name":"Strange Fruit by Billie Holiday","photo":"https://www.youtube.com/watch?v=-DGY9HvChXk"},
    {"id":35506267,"name":"Smoke on the Water by Deep Purple","photo":"https://www.youtube.com/watch?v=zUwEIt9ez7M"},
    {"id":16807306,"name":"Indian Reservation by The Raiders","photo":"ndian Reservation by The Raiders"},
    {"id":63521043,"name":"Zombie by The Cranberries","photo":"https://www.youtube.com/watch?v=6Ejga4kJUts"},
    {"id":91132400,"name":"The Big Bang Theory by The Barenaked Ladies","photo":"https://www.youtube.com/watch?v=TzhIfN4UQv8"},
    {"id":74127064,"name":"Mesopotamia by The B-52's","photo":"https://www.youtube.com/watch?v=0FyLcHxbSRk"},
    {"id":30283700,"name":"Run To The Hills by Iron Maiden","photo":"https://www.youtube.com/watch?v=86URGgqONvA"},
    {"id":40834926,"name":"Oliver's Army by Elvis Costello","photo":"https://www.youtube.com/watch?v=LrjHz5hrupA&t=30s"},
    {"id":59676726,"name":"The Trooper by Iron Maiden","photo":"https://www.youtube.com/watch?v=X4bgXH3sJ2Q"},
    {"id":18959030,"name":"Mister Custer by Larry Verne","photo":"https://www.youtube.com/watch?v=vXuPJNXjlRM"},
    {"id":19220801,"name":"Rasputin by Boney-M","photo":"https://www.youtube.com/watch?v=16y1AkoZkmQ"},
    {"id":41880845,"name":"Enola Gay by Orchestral Manoeuvres In The Dark","photo":"https://www.youtube.com/watch?v=d5XJ2GiR6Bo"},
    {"id":38744009,"name":"Raised by Wolves by U2","photo":"https://www.youtube.com/watch?v=xt0vGieEWFA"},
    {"id":46032709,"name":"P.L.U.C.K. by System of a Down","photo":"https://www.youtube.com/watch?v=VxVzT0znI8Q"},
    {"id":63172387,"name":"Brighter Than a Thousand Suns by Iron Maiden","photo":"https://www.youtube.com/watch?v=Cx_yCoPP1EY"},
    {"id":23127852,"name":"The Wreck of the Edmund Fitzgerald by Gordon Lightfoot","photo":"https://www.youtube.com/watch?v=9vST6hVRj2A"},
    {"id":91913599,"name":"The British Are Coming by Weezer","photo":"https://www.youtube.com/watch?v=jGUPsdOCZ-A"},
    {"id":34324158,"name":"The Longest Day by Iron Maiden","photo":"https://www.youtube.com/watch?v=JDCgvcH301A"},
    {"id":54027019,"name":"The Infanta by The Decemberists","photo":"https://www.youtube.com/watch?v=nFlTBJdpy5A"},
    {"id":49932101,"name":"Mississippi Goddam by Nina Simone","photo":"https://www.youtube.com/watch?v=LJ25-U3jNWM"},
    {"id":28040377,"name":"Battle of New Orleans by Johnny Horton","photo":"https://www.youtube.com/watch?v=__uFnEMJqjg"},
    {"id":34061331,"name":"Buffalo Soldier by Bob Marley","photo":"https://www.youtube.com/watch?v=S5FCdx7Dn0o"},
    {"id":24724551,"name":"American Witch by Rob Zombie","photo":"https://www.youtube.com/watch?v=MdKXShP_oc4"}
]